---
name: OpenTelemetry Collector
version: dev
slug: otelcol
description: Bring the OpenTelemetry collector into your home
url: "https://github.com/mcinnes01/ha-addon-otelcol"
ports:
  4317/tcp: null
  4318/tcp: null
ports_description:
  4317/tcp: OTLP/gRPC
  4318/tcp: OTLP/HTTP
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - config:rw
watchdog: http://[HOST]:13133/
apparmor: false
options:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      logging:
    # health-check is activated by default
    extensions:
      pprof:
      zpages:
    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
schema:
  config: "str"
image: "ghcr.io/mcinnes01/{arch}-ha-addon-otelcol"
